### PR TITLE
Tweak email validator

### LINKED ISSUE #2271: forgotPassword > Returned success response when user leave blank "Email" field
**Roles:** All

**Describe the bug**
forgotPassword > Returned success response when user leave blank `Email` field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
`Error` or `Input` validation message should be returned

**Actual Result**
Returned success response when user leave blank `Email` field

See video -  

https://user-images.githubusercontent.com/5212585/140915954-6b5fa757-0c11-43bf-92d3-e8a7601cb028.mp4

**GraphQL Query:(forgotPassword)**
image

**GraphQL response**
```
{
    "data": {
        "forgotPassword": true
    }
}
```

**Query and Input File**
[BugForgotPasswordEmailBlank.txt](https://github.com/SeedCompany/cord-api-v3/files/7504287/BugForgotPasswordEmailBlank.txt)

CordAPIV3# 600901f

### PR DESCRIPTION
**Pull request by daniel-leod**
Fixes #2271

### CODE REVIEW

**Review by CarsonF — APPROVED** [review]
LGTM!

File: src/common/validators/email.validator.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ export const IsEmail = (
       constraints: [options],
       validator: {
         validate: (value, args) =>
-          !value ||
+          !value === null ||
```
Comment (CarsonF) [inline src/common/validators/email.validator.ts:15]:
```suggestion
          value !== null ||
```

**Review by CarsonF — CHANGES_REQUESTED** [review]
I lied lol. Can you fix the negation?

**Review by CarsonF — APPROVED** [review]
