### PR TITLE
Fix #2087

### LINKED ISSUE #2087: Create Product > Getting "100" value in "progressTarget" field while user enter any values in  "progressTarget" input field
**Describe the bug**

Create Product > Getting `100` value in `progressTarget` field while user enter any values in  `progressTarget` input field

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
Given progress target value should be returned 

**Actual Result**
Getting `100` value in `progressTarget` field while user enter any values in  `progressTarget` input field

**GraphQL Query:(createProduct)**
progress_report_bug

**GraphQL response**
```
{
    "data": {
        "createProduct": {
            "product": {
                "id": "Z0csD5WJO7Y",
                "createdAt": "2021-08-16T09:01:41.042Z",
                "canDelete": true,
                "approach": "Visual",
                "legacyType": "JesusFilm",
                "progressTarget": {
                    "value": 100,
                    "canRead": true,
                    "canEdit": true
                },
                "describeCompletion": {
                    "value": "aa",
                    "canRead": true,
                    "canEdit": true
                },
                "progressOfCurrentReportDue": null,
                "mediums": {
                    "value": [
                        "Audio"
                    ],
                    "canEdit": true,
                    "canRead": true
                },
                "purposes": {
                    "value": [
                        "Discipleship"
                    ],
                    "canEdit": true,
                    "canRead": true
                },
                "methodology": {
                    "value": "OtherVisual",
                    "canEdit": true,
                    "canRead": true
                },
                "steps": {
                    "value": [
                        "BackTranslation"
                    ],
                    "canRead": true,
                    "canEdit": true
                },
                "scriptureReferences": {
                    "value": [
                        {
                            "start": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "label": "Genesis 3:4"
                            },
                            "end": {
                                "book": "Genesis",
                                "chapter": 3,
                                "verse": 4,
                                "label": "Genesis 3:4"
                            },
                            "label": "Genesis 3:4",
                            "totalVerses": 1
                        }
                    ],
                    "canEdit": true,
                    "canRead": true
                },
                "progressStepMeasurement": {
                    "value": "Percent",
                    "canRead": true,
                    "canEdit": true
                },
                "progressReports": [
                    {
                        "product": {
                            "id": "Z0csD5WJO7Y"
                        },
                        "report": {
                            "id": "wsR7SF22bhV"
                        },
                        "steps": [
                            {
                                "completed": {
                                    "value": null,
                                    "canRead": true,
                                    "canEdit": false
                                },
                                "step": "BackTranslation"
                            }
                        ]
                    },
                    {
                        "product": {
                            "id": "Z0csD5WJO7Y"
                        },
                        "report": {
                            "id": "0KMas0DgYKI"
                        },
                        "steps": [
                            {
                                "completed": {
                                    "value": null,
                                    "canRead": true,
                                    "canEdit": false
                                },
                                "step": "BackTranslation"
                            }
                        ]
                    },
                    {
                        "product": {
                            "id": "Z0csD5WJO7Y"
                        },
                        "report": {
                            "id": "YKRusGEUDGZ"
                        },
                        "steps": [
                            {
                                "completed": {
                                    "value": null,
                                    "canRead": true,
                                    "canEdit": false
                                },
                                "step": "BackTranslation"
                            }
                        ]
                    },
                    {
                        "product": {
                            "id": "Z0csD5WJO7Y"
                        },
                        "report": {
                            "id": "0JfkfjjHE5L"
                        },
                        "steps": [
                            {
                                "completed": {
                                    "value": null,
                                    "canRead": true,
                                    "canEdit": false
                                },
                                "step": "BackTranslation"
                            }
                        ]
                    }
                ]
            }
        }
    },
```
**Query and Input File:**
[progressTarget_bug.txt](https://github.com/SeedCompany/cord-api-v3/files/7021690/progressTarget_bug.txt)

CordAPIV3# 9190940

### PR DESCRIPTION
**Pull request by daniel-leod**
Fixes #2087

### CODE REVIEW

File: src/components/product/product.repository.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ export class ProductRepository extends CommonRepository {
             {
               // BC with existing products
               progressStepMeasurement: `"${ProgressMeasurement.Percent}"`,
-              progressTarget: 100,
+              progressTarget: 'props.progressTarget',
```
Comment (CarsonF) [inline src/components/product/product.repository.ts:108]: This is for products already existing that don't have `props.progressTarget`. The `merge()` should take the `progressTarget` from `props`, if it exists, instead of this default/fallback.

**Review by CarsonF — APPROVED** [review]
Thanks @daniel-leod looks great!
